
#include "capi.h"

void
rcl_define_opencl_constants(VALUE mod)
{

#define RCL_DEF_CONSTANT(constant) \
    do \
        rb_define_const(mod, #constant, INT2FIX(constant)); \
    while (0)

    // cl_addressing_mode
    RCL_DEF_CONSTANT(CL_ADDRESS_NONE);
    RCL_DEF_CONSTANT(CL_ADDRESS_CLAMP_TO_EDGE);
    RCL_DEF_CONSTANT(CL_ADDRESS_CLAMP);
    RCL_DEF_CONSTANT(CL_ADDRESS_REPEAT);

    // cl_bool
    RCL_DEF_CONSTANT(CL_FALSE);
    RCL_DEF_CONSTANT(CL_TRUE);

    // cl_build_status
    RCL_DEF_CONSTANT(CL_BUILD_ERROR);
    RCL_DEF_CONSTANT(CL_BUILD_IN_PROGRESS);
    RCL_DEF_CONSTANT(CL_BUILD_NONE);
    RCL_DEF_CONSTANT(CL_BUILD_SUCCESS);

#ifdef CL_VERSION_1_1
    //￼cl_buffer_create_type
    RCL_DEF_CONSTANT(CL_BUFFER_CREATE_TYPE_REGION);
#endif

    // cl_channel_order
    RCL_DEF_CONSTANT(CL_A);
    RCL_DEF_CONSTANT(CL_R);
    RCL_DEF_CONSTANT(CL_RG);
    RCL_DEF_CONSTANT(CL_RA);
    RCL_DEF_CONSTANT(CL_RGB);
    RCL_DEF_CONSTANT(CL_RGBA);
    RCL_DEF_CONSTANT(CL_BGRA);
    RCL_DEF_CONSTANT(CL_ARGB);
    RCL_DEF_CONSTANT(CL_INTENSITY);
    RCL_DEF_CONSTANT(CL_LUMINANCE);
#ifdef CL_VERSION_1_1
    RCL_DEF_CONSTANT(CL_Rx);
    RCL_DEF_CONSTANT(CL_RGx);
    RCL_DEF_CONSTANT(CL_RGBx);
#endif

    // cl_channel_type
    RCL_DEF_CONSTANT(CL_FLOAT);
    RCL_DEF_CONSTANT(CL_HALF_FLOAT);
    RCL_DEF_CONSTANT(CL_SIGNED_INT16);
    RCL_DEF_CONSTANT(CL_SIGNED_INT32);
    RCL_DEF_CONSTANT(CL_SIGNED_INT8);
    RCL_DEF_CONSTANT(CL_SNORM_INT8);
    RCL_DEF_CONSTANT(CL_SNORM_INT16);
    RCL_DEF_CONSTANT(CL_UNORM_INT_101010);
    RCL_DEF_CONSTANT(CL_UNORM_INT16);
    RCL_DEF_CONSTANT(CL_UNORM_INT8);
    RCL_DEF_CONSTANT(CL_UNORM_SHORT_555);
    RCL_DEF_CONSTANT(CL_UNORM_SHORT_565);
    RCL_DEF_CONSTANT(CL_UNSIGNED_INT16);
    RCL_DEF_CONSTANT(CL_UNSIGNED_INT32);
    RCL_DEF_CONSTANT(CL_UNSIGNED_INT8);

    // cl_command_queue_info
    RCL_DEF_CONSTANT(CL_QUEUE_CONTEXT);
    RCL_DEF_CONSTANT(CL_QUEUE_DEVICE);
    RCL_DEF_CONSTANT(CL_QUEUE_REFERENCE_COUNT);
    RCL_DEF_CONSTANT(CL_QUEUE_PROPERTIES);

    // cl_command_queue_properties
    RCL_DEF_CONSTANT(CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE);
    RCL_DEF_CONSTANT(CL_QUEUE_PROFILING_ENABLE);

    // cl_command_type
    RCL_DEF_CONSTANT(CL_COMMAND_ACQUIRE_GL_OBJECTS);
    RCL_DEF_CONSTANT(CL_COMMAND_COPY_BUFFER);
    RCL_DEF_CONSTANT(CL_COMMAND_COPY_BUFFER_TO_IMAGE);
    RCL_DEF_CONSTANT(CL_COMMAND_COPY_IMAGE);
    RCL_DEF_CONSTANT(CL_COMMAND_COPY_IMAGE_TO_BUFFER);
    RCL_DEF_CONSTANT(CL_COMMAND_MAP_BUFFER);
    RCL_DEF_CONSTANT(CL_COMMAND_MAP_IMAGE);
    RCL_DEF_CONSTANT(CL_COMMAND_MARKER);
    RCL_DEF_CONSTANT(CL_COMMAND_NATIVE_KERNEL);
    RCL_DEF_CONSTANT(CL_COMMAND_NDRANGE_KERNEL);
    RCL_DEF_CONSTANT(CL_COMMAND_READ_BUFFER);
    RCL_DEF_CONSTANT(CL_COMMAND_READ_IMAGE);
    RCL_DEF_CONSTANT(CL_COMMAND_RELEASE_GL_OBJECTS);
    RCL_DEF_CONSTANT(CL_COMMAND_TASK);
    RCL_DEF_CONSTANT(CL_COMMAND_UNMAP_MEM_OBJECT);
    RCL_DEF_CONSTANT(CL_COMMAND_WRITE_BUFFER);
    RCL_DEF_CONSTANT(CL_COMMAND_WRITE_IMAGE);

    // cl_context_info
    RCL_DEF_CONSTANT(CL_CONTEXT_REFERENCE_COUNT);
    RCL_DEF_CONSTANT(CL_CONTEXT_DEVICES);
    RCL_DEF_CONSTANT(CL_CONTEXT_PROPERTIES);
#ifdef CL_VERSION_1_1
    RCL_DEF_CONSTANT(CL_CONTEXT_NUM_DEVICES);
#endif

    // cl_context_properties
    RCL_DEF_CONSTANT(CL_CONTEXT_PLATFORM);

    // cl_device_exec_capabilities
    RCL_DEF_CONSTANT(CL_EXEC_KERNEL);
    RCL_DEF_CONSTANT(CL_EXEC_NATIVE_KERNEL);

    // cl_device_fp_config
    RCL_DEF_CONSTANT(CL_FP_DENORM);
    RCL_DEF_CONSTANT(CL_FP_FMA);
    RCL_DEF_CONSTANT(CL_FP_INF_NAN);
    RCL_DEF_CONSTANT(CL_FP_ROUND_TO_INF);
    RCL_DEF_CONSTANT(CL_FP_ROUND_TO_NEAREST);
    RCL_DEF_CONSTANT(CL_FP_ROUND_TO_ZERO);

    // cl_device_info
    RCL_DEF_CONSTANT(CL_DEVICE_ADDRESS_BITS);
    RCL_DEF_CONSTANT(CL_DEVICE_AVAILABLE);
    RCL_DEF_CONSTANT(CL_DEVICE_COMPILER_AVAILABLE);
    RCL_DEF_CONSTANT(CL_DEVICE_ENDIAN_LITTLE);
    RCL_DEF_CONSTANT(CL_DEVICE_ERROR_CORRECTION_SUPPORT);
    RCL_DEF_CONSTANT(CL_DEVICE_EXECUTION_CAPABILITIES);
    RCL_DEF_CONSTANT(CL_DEVICE_EXTENSIONS);
    RCL_DEF_CONSTANT(CL_DEVICE_GLOBAL_MEM_CACHE_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_GLOBAL_MEM_CACHE_TYPE);
    RCL_DEF_CONSTANT(CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_GLOBAL_MEM_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_IMAGE_SUPPORT);
    RCL_DEF_CONSTANT(CL_DEVICE_IMAGE2D_MAX_HEIGHT);
    RCL_DEF_CONSTANT(CL_DEVICE_IMAGE2D_MAX_WIDTH);
    RCL_DEF_CONSTANT(CL_DEVICE_IMAGE3D_MAX_DEPTH);
    RCL_DEF_CONSTANT(CL_DEVICE_IMAGE3D_MAX_HEIGHT);
    RCL_DEF_CONSTANT(CL_DEVICE_IMAGE3D_MAX_WIDTH);
    RCL_DEF_CONSTANT(CL_DEVICE_LOCAL_MEM_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_LOCAL_MEM_TYPE);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_CLOCK_FREQUENCY);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_COMPUTE_UNITS);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_CONSTANT_ARGS);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_MEM_ALLOC_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_PARAMETER_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_READ_IMAGE_ARGS);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_SAMPLERS);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_WORK_GROUP_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_WORK_ITEM_SIZES);
    RCL_DEF_CONSTANT(CL_DEVICE_MAX_WRITE_IMAGE_ARGS);
    RCL_DEF_CONSTANT(CL_DEVICE_MEM_BASE_ADDR_ALIGN);
    RCL_DEF_CONSTANT(CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE);
    RCL_DEF_CONSTANT(CL_DEVICE_NAME);
    RCL_DEF_CONSTANT(CL_DEVICE_PLATFORM);
    RCL_DEF_CONSTANT(CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR);
    RCL_DEF_CONSTANT(CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE);
    RCL_DEF_CONSTANT(CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT);
    RCL_DEF_CONSTANT(CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT);
    RCL_DEF_CONSTANT(CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG);
    RCL_DEF_CONSTANT(CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT);
    RCL_DEF_CONSTANT(CL_DEVICE_PROFILE);
    RCL_DEF_CONSTANT(CL_DEVICE_PROFILING_TIMER_RESOLUTION);
    RCL_DEF_CONSTANT(CL_DEVICE_QUEUE_PROPERTIES);
    RCL_DEF_CONSTANT(CL_DEVICE_SINGLE_FP_CONFIG);
    RCL_DEF_CONSTANT(CL_DEVICE_TYPE);
    RCL_DEF_CONSTANT(CL_DEVICE_VENDOR_ID);
    RCL_DEF_CONSTANT(CL_DEVICE_VENDOR);
    RCL_DEF_CONSTANT(CL_DEVICE_VERSION);
    RCL_DEF_CONSTANT(CL_DRIVER_VERSION);
#ifdef CL_VERSION_1_1
    RCL_DEF_CONSTANT(CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR);
    RCL_DEF_CONSTANT(CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT);
    RCL_DEF_CONSTANT(CL_DEVICE_NATIVE_VECTOR_WIDTH_INT);
    RCL_DEF_CONSTANT(CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG);
    RCL_DEF_CONSTANT(CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT);
    RCL_DEF_CONSTANT(CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE);
    RCL_DEF_CONSTANT(CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF);
    RCL_DEF_CONSTANT(CL_DEVICE_HOST_UNIFIED_MEMORY);
    RCL_DEF_CONSTANT(CL_DEVICE_OPENCL_C_VERSION);
#endif

    // cl_device_local_mem_type
    RCL_DEF_CONSTANT(CL_GLOBAL);
    RCL_DEF_CONSTANT(CL_LOCAL);

    // cl_device_mem_cache_type
    RCL_DEF_CONSTANT(CL_NONE);
    RCL_DEF_CONSTANT(CL_READ_ONLY_CACHE);
    RCL_DEF_CONSTANT(CL_READ_WRITE_CACHE);

    // cl_device_type
    RCL_DEF_CONSTANT(CL_DEVICE_TYPE_CPU);
    RCL_DEF_CONSTANT(CL_DEVICE_TYPE_GPU);
    RCL_DEF_CONSTANT(CL_DEVICE_TYPE_ACCELERATOR);
    RCL_DEF_CONSTANT(CL_DEVICE_TYPE_DEFAULT);
    RCL_DEF_CONSTANT(CL_DEVICE_TYPE_ALL);

    // cl_event_info
    RCL_DEF_CONSTANT(CL_EVENT_COMMAND_QUEUE);
    RCL_DEF_CONSTANT(CL_EVENT_COMMAND_TYPE);
    RCL_DEF_CONSTANT(CL_EVENT_REFERENCE_COUNT);
    RCL_DEF_CONSTANT(CL_EVENT_COMMAND_EXECUTION_STATUS);

    // cl_int
    RCL_DEF_CONSTANT(CL_QUEUED);
    RCL_DEF_CONSTANT(CL_SUBMITTED);
    RCL_DEF_CONSTANT(CL_RUNNING);
    RCL_DEF_CONSTANT(CL_COMPLETE);

    // cl_filter_mode
    RCL_DEF_CONSTANT(CL_FILTER_NEAREST);
    RCL_DEF_CONSTANT(CL_FILTER_LINEAR);

    // cl_gl_object_type
    RCL_DEF_CONSTANT(CL_GL_OBJECT_BUFFER);
    RCL_DEF_CONSTANT(CL_GL_OBJECT_TEXTURE2D);
    RCL_DEF_CONSTANT(CL_GL_OBJECT_TEXTURE3D);
    RCL_DEF_CONSTANT(CL_GL_OBJECT_RENDERBUFFER);

    // cl_gl_texture_info
    RCL_DEF_CONSTANT(CL_GL_TEXTURE_TARGET);
    RCL_DEF_CONSTANT(CL_GL_MIPMAP_LEVEL);

    // cl_image_info
    RCL_DEF_CONSTANT(CL_IMAGE_FORMAT);
    RCL_DEF_CONSTANT(CL_IMAGE_ELEMENT_SIZE);
    RCL_DEF_CONSTANT(CL_IMAGE_ROW_PITCH);
    RCL_DEF_CONSTANT(CL_IMAGE_SLICE_PITCH);
    RCL_DEF_CONSTANT(CL_IMAGE_WIDTH);
    RCL_DEF_CONSTANT(CL_IMAGE_HEIGHT);
    RCL_DEF_CONSTANT(CL_IMAGE_DEPTH);

    // cl_kernel_info
    RCL_DEF_CONSTANT(CL_KERNEL_FUNCTION_NAME);
    RCL_DEF_CONSTANT(CL_KERNEL_NUM_ARGS);
    RCL_DEF_CONSTANT(CL_KERNEL_REFERENCE_COUNT);
    RCL_DEF_CONSTANT(CL_KERNEL_CONTEXT);
    RCL_DEF_CONSTANT(CL_KERNEL_PROGRAM);

    // cl_kernel_work_group_info
    RCL_DEF_CONSTANT(CL_KERNEL_WORK_GROUP_SIZE);
    RCL_DEF_CONSTANT(CL_KERNEL_COMPILE_WORK_GROUP_SIZE);
    RCL_DEF_CONSTANT(CL_KERNEL_LOCAL_MEM_SIZE);
#ifdef CL_VERSION_1_1
    RCL_DEF_CONSTANT(CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE);
#endif
    // cl_map_flags
    RCL_DEF_CONSTANT(CL_MAP_READ);
    RCL_DEF_CONSTANT(CL_MAP_WRITE);

    // cl_mem_flags
    RCL_DEF_CONSTANT(CL_MEM_READ_WRITE);
    RCL_DEF_CONSTANT(CL_MEM_WRITE_ONLY);
    RCL_DEF_CONSTANT(CL_MEM_READ_ONLY);
    RCL_DEF_CONSTANT(CL_MEM_USE_HOST_PTR);
    RCL_DEF_CONSTANT(CL_MEM_ALLOC_HOST_PTR);
    RCL_DEF_CONSTANT(CL_MEM_COPY_HOST_PTR);

    // cl_mem_info
    RCL_DEF_CONSTANT(CL_MEM_TYPE);
    RCL_DEF_CONSTANT(CL_MEM_FLAGS);
    RCL_DEF_CONSTANT(CL_MEM_SIZE);
    RCL_DEF_CONSTANT(CL_MEM_HOST_PTR);
    RCL_DEF_CONSTANT(CL_MEM_MAP_COUNT);
    RCL_DEF_CONSTANT(CL_MEM_REFERENCE_COUNT);
    RCL_DEF_CONSTANT(CL_MEM_CONTEXT);

    // cl_mem_object_type
    RCL_DEF_CONSTANT(CL_MEM_OBJECT_BUFFER);
    RCL_DEF_CONSTANT(CL_MEM_OBJECT_IMAGE2D);
    RCL_DEF_CONSTANT(CL_MEM_OBJECT_IMAGE3D);

    // cl_platform_info
    RCL_DEF_CONSTANT(CL_PLATFORM_PROFILE);
    RCL_DEF_CONSTANT(CL_PLATFORM_VERSION);
    RCL_DEF_CONSTANT(CL_PLATFORM_NAME);
    RCL_DEF_CONSTANT(CL_PLATFORM_VENDOR);
    RCL_DEF_CONSTANT(CL_PLATFORM_EXTENSIONS);

    // cl_profiling_info
    RCL_DEF_CONSTANT(CL_PROFILING_COMMAND_QUEUED);
    RCL_DEF_CONSTANT(CL_PROFILING_COMMAND_SUBMIT);
    RCL_DEF_CONSTANT(CL_PROFILING_COMMAND_START);
    RCL_DEF_CONSTANT(CL_PROFILING_COMMAND_END);

    // cl_program_info
    RCL_DEF_CONSTANT(CL_PROGRAM_REFERENCE_COUNT);
    RCL_DEF_CONSTANT(CL_PROGRAM_CONTEXT);
    RCL_DEF_CONSTANT(CL_PROGRAM_NUM_DEVICES);
    RCL_DEF_CONSTANT(CL_PROGRAM_DEVICES);
    RCL_DEF_CONSTANT(CL_PROGRAM_SOURCE);
    RCL_DEF_CONSTANT(CL_PROGRAM_BINARY_SIZES);
    RCL_DEF_CONSTANT(CL_PROGRAM_BINARIES);

    // cl_program_build_info
    RCL_DEF_CONSTANT(CL_PROGRAM_BUILD_STATUS);
    RCL_DEF_CONSTANT(CL_PROGRAM_BUILD_OPTIONS);
    RCL_DEF_CONSTANT(CL_PROGRAM_BUILD_LOG);

    // cl_sampler_info
    RCL_DEF_CONSTANT(CL_SAMPLER_REFERENCE_COUNT);
    RCL_DEF_CONSTANT(CL_SAMPLER_CONTEXT);
    RCL_DEF_CONSTANT(CL_SAMPLER_NORMALIZED_COORDS);
    RCL_DEF_CONSTANT(CL_SAMPLER_ADDRESSING_MODE);
    RCL_DEF_CONSTANT(CL_SAMPLER_FILTER_MODE);

#ifdef CL_VERSION_1_1
    // cl_version
    RCL_DEF_CONSTANT(CL_VERSION_1_1);
#endif
}
